apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
percentageOfNodesToScore: 100
profiles:
  - schedulerName: simon-scheduler
    plugins:
      filter:
        enabled:
          - name: Open-Local
          - name: Open-Gpu-Share
      preScore:
        disabled:
          - name: Gpu-Share-Frag-Sim-Score
          - name: Gpu-Share-Frag-Sim-Norm-Score
          - name: Gpu-Frag-Sim-Score
        enabled:
      score:
        disabled:
          - name: Gpu-Frag-Score
          - name: Gpu-Frag-Score-Bellman
          - name: Gpu-Share-Frag-Score
          - name: Gpu-Share-Frag-Sim-Score
          - name: Gpu-Packing-Score
          - name: Gpu-Packing-Sim-Score
          - name: CosineSimilarityScore
          - name: CosineSimPackingScore
          - name: BestFitScore
          - name: Simon
          - name: WorstFitScore
          - name: DotProductScore
          - name: L2NormDiffScore
          - name: L2NormRatioScore
          - name: GandivaScore
          - name: SynergyScore

          - name: ImageLocality
          - name: NodeAffinity
          - name: PodTopologySpread
          - name: TaintToleration
          - name: NodeResourcesBalancedAllocation
          - name: InterPodAffinity
          - name: NodeResourcesLeastAllocated
          - name: NodePreferAvoidPods
        enabled:
          - name: GandivaScore
            weight: 1000
      reserve:
        enabled:
          - name: Open-Gpu-Share
      bind:
        disabled:
          - name: DefaultBinder
          - name: Open-Local
        enabled:
          - name: Simon
    pluginConfig:
      - name: DotProductScore
        args:
          dimExtMethod: divide
      - name: CosineSimilarityScore
        args:
          dimExtMethod: divide
          normMethod: node
      - name: Open-Gpu-Share
        args:
#          dimExtMethod: divide
#          normMethod: node
          gpuSelMethod: best